### ISSUE TITLE
voxel metadata

### ISSUE THREAD

**Issue by fcollman** [janelia-flyem/diced#7]
There should be a way to set and get the dvid metadata through diced directly.  Something like I also tried to figure out how to do it through libdvid in python, but I couldn't figure out how to construct a libdvid:BinaryData object for this signature
```
custom_request(libdvid::DVIDNodeService {lvalue}, std::string endpoint, boost::shared_ptr<libdvid::BinaryData> payload, libdvid::ConnectionMethod method, bool compress=False, unsigned long long datasize=1)
```
which is what I think I need to post a get or set on the resolution of an array.. assuming i have a DicedRepo named repo, and a DicedArray with the alias 'my_array'.

```
node_service=libdvid.DVIDNodeService('localhost:8000',repo.uuid)
answer=node_service.custom_request('my_array/resolution',[3,3,50],'POST')
```
I would need to convert the 3,3,50 to a libdvid:BinaryData object?

I saw the method node_service.get_typeinfo('my_array'), which gives a dictionary with the VoxelSize.. but there didn't appear to be an analogous set method.

**Comment by stephenplaza** [comment]
For now, the diced API represents the recommended features to use with DVID.  In time, more of these DVID features will be exposed (or augmented) in the diced interface.  It basically represents what I can very cleanly and easily expose in a convenient manner.

That being said, power-users will likely want to access features directly in DVID, and therefore call the REST api.  In this example, using libdvid is the correct thing to do.  The BinaryData object is just a string in python.  Try json.dumps([3,3,50]) and see if that works.  You might need a leading parentheses to 'myarray/resolution' but I don't remember off the top of my head.

There is no set_typeinfo.  The resolution was something that is intended to be set on datatype creation.  diced only exposed extents since resolution is information is not intrinsically used in DVID operations.  If you have new endpoint requests for the DVID API, please note in the DVID repo.

**Comment by fcollman** [comment]
Thanks, makes sense.  

I'll still put in a plug then for a future enhancement of a keyword argument of DicedRepo.create_array  of VoxelResolution=[8,8,8], which passes through to the libdvid call for creating the array with that resolution.

fwiw, i tried the json.dumps([3,3,50]) and i got the same error.. but turns out my problem was the "POST"

this worked
```
answer=node_service.custom_request('MN_global_annotation/resolution',json.dumps([3,3,50]),libdvid.ConnectionMethod.POST)
```
